//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ortopedia.UI.OrtopediaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrtopediaService.IOrtopediaService")]
    public interface IOrtopediaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneMailsEmpresa", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneMailsEmpresaResponse")]
        System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneTelefonosEmpresa", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneTelefonosEmpresaResponse")]
        System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ValidaExistenciaEmpresa", ReplyAction="http://tempuri.org/IOrtopediaService/ValidaExistenciaEmpresaResponse")]
        string ValidaExistenciaEmpresa(Ortopedia.BE.EmpresasBE empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneListaAcreedores", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneListaAcreedoresResponse")]
        System.Collections.Generic.List<Ortopedia.BE.AcreedoresBE> ObtieneListaAcreedores(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/InsertaAcreedor", ReplyAction="http://tempuri.org/IOrtopediaService/InsertaAcreedorResponse")]
        bool InsertaAcreedor(Ortopedia.BE.AcreedoresBE acreedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneMailsAcreedor", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneMailsAcreedorResponse")]
        System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsAcreedor(int idAcreedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneTelefonosAcreedor", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneTelefonosAcreedorResponse")]
        System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosAcreedor(int idAcreedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneDireccionesAcreedor", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneDireccionesAcreedorResponse")]
        System.Collections.Generic.List<Ortopedia.BE.DireccionesBE> ObtieneDireccionesAcreedor(int idAcreedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ValidaExistenciaAcreedor", ReplyAction="http://tempuri.org/IOrtopediaService/ValidaExistenciaAcreedorResponse")]
        string ValidaExistenciaAcreedor(Ortopedia.BE.AcreedoresBE acreedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneCatalogosGenerales", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneCatalogosGeneralesResponse")]
        System.Collections.Generic.List<Ortopedia.BE.CatalogosBE> ObtieneCatalogosGenerales(int tipoCatalogo, string filtro1, string filtro2, string filtro3, string filtro4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneCatalogo", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneCatalogoResponse")]
        System.Collections.Generic.List<Ortopedia.BE.CatalogosBE> ObtieneCatalogo(string filtro1, string filtro2, string filtro3, string filtro4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/GuardaCatalogo", ReplyAction="http://tempuri.org/IOrtopediaService/GuardaCatalogoResponse")]
        bool GuardaCatalogo(Ortopedia.BE.CatalogosBE catalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneListaMedicos", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneListaMedicosResponse")]
        System.Collections.Generic.List<Ortopedia.BE.MedicosBE> ObtieneListaMedicos(string nombre, string appaterno, string apmaterno, int especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/InsertaMedico", ReplyAction="http://tempuri.org/IOrtopediaService/InsertaMedicoResponse")]
        bool InsertaMedico(Ortopedia.BE.MedicosBE medico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneMailsMedico", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneMailsMedicoResponse")]
        System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsMedico(int idMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneTelefonosMedico", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneTelefonosMedicoResponse")]
        System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosMedico(int idMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ValidaExistenciaMedico", ReplyAction="http://tempuri.org/IOrtopediaService/ValidaExistenciaMedicoResponse")]
        string ValidaExistenciaMedico(Ortopedia.BE.MedicosBE medico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneListaClientes", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneListaClientesResponse")]
        System.Collections.Generic.List<Ortopedia.BE.ClientesBE> ObtieneListaClientes(string nombre, string appaterno, string apmaterno, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/InsertaCliente", ReplyAction="http://tempuri.org/IOrtopediaService/InsertaClienteResponse")]
        bool InsertaCliente(Ortopedia.BE.ClientesBE cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneMailsCliente", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneMailsClienteResponse")]
        System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsCliente(int idClienteFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneTelefonosCliente", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneTelefonosClienteResponse")]
        System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosCliente(int idClienteFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ValidaExistenciaCliente", ReplyAction="http://tempuri.org/IOrtopediaService/ValidaExistenciaClienteResponse")]
        string ValidaExistenciaCliente(Ortopedia.BE.ClientesBE cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneListaPacientes", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneListaPacientesResponse")]
        System.Collections.Generic.List<Ortopedia.BE.PacientesBE> ObtieneListaPacientes(string nombre, string appaterno, string apmaterno, string curp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/InsertaPaciente", ReplyAction="http://tempuri.org/IOrtopediaService/InsertaPacienteResponse")]
        bool InsertaPaciente(Ortopedia.BE.PacientesBE paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneMailsPaciente", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneMailsPacienteResponse")]
        System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsPaciente(int idPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneTelefonosPaciente", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneTelefonosPacienteResponse")]
        System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosPaciente(int idPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneDireccionesPaciente", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneDireccionesPacienteResponse")]
        System.Collections.Generic.List<Ortopedia.BE.DireccionesBE> ObtieneDireccionesPaciente(int idPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ValidaExistenciaPaciente", ReplyAction="http://tempuri.org/IOrtopediaService/ValidaExistenciaPacienteResponse")]
        string ValidaExistenciaPaciente(Ortopedia.BE.PacientesBE paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneListaProveedores", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneListaProveedoresResponse")]
        System.Collections.Generic.List<Ortopedia.BE.ProveedoresBE> ObtieneListaProveedores(string nombre, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/InsertaProveedor", ReplyAction="http://tempuri.org/IOrtopediaService/InsertaProveedorResponse")]
        bool InsertaProveedor(Ortopedia.BE.ProveedoresBE Proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneMailsProveedor", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneMailsProveedorResponse")]
        System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsProveedor(int idProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneTelefonosProveedor", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneTelefonosProveedorResponse")]
        System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosProveedor(int idProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneDireccionesProveedor", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneDireccionesProveedorResponse")]
        System.Collections.Generic.List<Ortopedia.BE.DireccionesBE> ObtieneDireccionesProveedor(int idProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneCuentasProveedor", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneCuentasProveedorResponse")]
        System.Collections.Generic.List<Ortopedia.BE.CuentasBE> ObtieneCuentasProveedor(int idProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ValidaExistenciaProveedor", ReplyAction="http://tempuri.org/IOrtopediaService/ValidaExistenciaProveedorResponse")]
        string ValidaExistenciaProveedor(Ortopedia.BE.ProveedoresBE proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/ObtieneListaEmpresas", ReplyAction="http://tempuri.org/IOrtopediaService/ObtieneListaEmpresasResponse")]
        System.Collections.Generic.List<Ortopedia.BE.EmpresasBE> ObtieneListaEmpresas(string nombre, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrtopediaService/InsertaEmpresa", ReplyAction="http://tempuri.org/IOrtopediaService/InsertaEmpresaResponse")]
        bool InsertaEmpresa(Ortopedia.BE.EmpresasBE empresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrtopediaServiceChannel : Ortopedia.UI.OrtopediaService.IOrtopediaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrtopediaServiceClient : System.ServiceModel.ClientBase<Ortopedia.UI.OrtopediaService.IOrtopediaService>, Ortopedia.UI.OrtopediaService.IOrtopediaService {
        
        public OrtopediaServiceClient() {
        }
        
        public OrtopediaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrtopediaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrtopediaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrtopediaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsEmpresa(int idEmpresa) {
            return base.Channel.ObtieneMailsEmpresa(idEmpresa);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosEmpresa(int idEmpresa) {
            return base.Channel.ObtieneTelefonosEmpresa(idEmpresa);
        }
        
        public string ValidaExistenciaEmpresa(Ortopedia.BE.EmpresasBE empresa) {
            return base.Channel.ValidaExistenciaEmpresa(empresa);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.AcreedoresBE> ObtieneListaAcreedores(string nombre) {
            return base.Channel.ObtieneListaAcreedores(nombre);
        }
        
        public bool InsertaAcreedor(Ortopedia.BE.AcreedoresBE acreedor) {
            return base.Channel.InsertaAcreedor(acreedor);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsAcreedor(int idAcreedor) {
            return base.Channel.ObtieneMailsAcreedor(idAcreedor);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosAcreedor(int idAcreedor) {
            return base.Channel.ObtieneTelefonosAcreedor(idAcreedor);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.DireccionesBE> ObtieneDireccionesAcreedor(int idAcreedor) {
            return base.Channel.ObtieneDireccionesAcreedor(idAcreedor);
        }
        
        public string ValidaExistenciaAcreedor(Ortopedia.BE.AcreedoresBE acreedor) {
            return base.Channel.ValidaExistenciaAcreedor(acreedor);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.CatalogosBE> ObtieneCatalogosGenerales(int tipoCatalogo, string filtro1, string filtro2, string filtro3, string filtro4) {
            return base.Channel.ObtieneCatalogosGenerales(tipoCatalogo, filtro1, filtro2, filtro3, filtro4);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.CatalogosBE> ObtieneCatalogo(string filtro1, string filtro2, string filtro3, string filtro4) {
            return base.Channel.ObtieneCatalogo(filtro1, filtro2, filtro3, filtro4);
        }
        
        public bool GuardaCatalogo(Ortopedia.BE.CatalogosBE catalogo) {
            return base.Channel.GuardaCatalogo(catalogo);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.MedicosBE> ObtieneListaMedicos(string nombre, string appaterno, string apmaterno, int especialidad) {
            return base.Channel.ObtieneListaMedicos(nombre, appaterno, apmaterno, especialidad);
        }
        
        public bool InsertaMedico(Ortopedia.BE.MedicosBE medico) {
            return base.Channel.InsertaMedico(medico);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsMedico(int idMedico) {
            return base.Channel.ObtieneMailsMedico(idMedico);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosMedico(int idMedico) {
            return base.Channel.ObtieneTelefonosMedico(idMedico);
        }
        
        public string ValidaExistenciaMedico(Ortopedia.BE.MedicosBE medico) {
            return base.Channel.ValidaExistenciaMedico(medico);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.ClientesBE> ObtieneListaClientes(string nombre, string appaterno, string apmaterno, string rfc) {
            return base.Channel.ObtieneListaClientes(nombre, appaterno, apmaterno, rfc);
        }
        
        public bool InsertaCliente(Ortopedia.BE.ClientesBE cliente) {
            return base.Channel.InsertaCliente(cliente);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsCliente(int idClienteFiscal) {
            return base.Channel.ObtieneMailsCliente(idClienteFiscal);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosCliente(int idClienteFiscal) {
            return base.Channel.ObtieneTelefonosCliente(idClienteFiscal);
        }
        
        public string ValidaExistenciaCliente(Ortopedia.BE.ClientesBE cliente) {
            return base.Channel.ValidaExistenciaCliente(cliente);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.PacientesBE> ObtieneListaPacientes(string nombre, string appaterno, string apmaterno, string curp) {
            return base.Channel.ObtieneListaPacientes(nombre, appaterno, apmaterno, curp);
        }
        
        public bool InsertaPaciente(Ortopedia.BE.PacientesBE paciente) {
            return base.Channel.InsertaPaciente(paciente);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsPaciente(int idPaciente) {
            return base.Channel.ObtieneMailsPaciente(idPaciente);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosPaciente(int idPaciente) {
            return base.Channel.ObtieneTelefonosPaciente(idPaciente);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.DireccionesBE> ObtieneDireccionesPaciente(int idPaciente) {
            return base.Channel.ObtieneDireccionesPaciente(idPaciente);
        }
        
        public string ValidaExistenciaPaciente(Ortopedia.BE.PacientesBE paciente) {
            return base.Channel.ValidaExistenciaPaciente(paciente);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.ProveedoresBE> ObtieneListaProveedores(string nombre, string rfc) {
            return base.Channel.ObtieneListaProveedores(nombre, rfc);
        }
        
        public bool InsertaProveedor(Ortopedia.BE.ProveedoresBE Proveedor) {
            return base.Channel.InsertaProveedor(Proveedor);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.MailsBE> ObtieneMailsProveedor(int idProveedor) {
            return base.Channel.ObtieneMailsProveedor(idProveedor);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.TelefonosBE> ObtieneTelefonosProveedor(int idProveedor) {
            return base.Channel.ObtieneTelefonosProveedor(idProveedor);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.DireccionesBE> ObtieneDireccionesProveedor(int idProveedor) {
            return base.Channel.ObtieneDireccionesProveedor(idProveedor);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.CuentasBE> ObtieneCuentasProveedor(int idProveedor) {
            return base.Channel.ObtieneCuentasProveedor(idProveedor);
        }
        
        public string ValidaExistenciaProveedor(Ortopedia.BE.ProveedoresBE proveedor) {
            return base.Channel.ValidaExistenciaProveedor(proveedor);
        }
        
        public System.Collections.Generic.List<Ortopedia.BE.EmpresasBE> ObtieneListaEmpresas(string nombre, string rfc) {
            return base.Channel.ObtieneListaEmpresas(nombre, rfc);
        }
        
        public bool InsertaEmpresa(Ortopedia.BE.EmpresasBE empresa) {
            return base.Channel.InsertaEmpresa(empresa);
        }
    }
}
